"""02_rates_unique_constraint

Revision ID: 3498d9c02b5f
Revises: 75e93b8b8d0e
Create Date: 2025-02-14 22:01:36.832150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3498d9c02b5f'
down_revision: Union[str, None] = '75e93b8b8d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('currency_date_uc', 'currency_rates', ['from_cur', 'to_cur', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('currency_date_uc', 'currency_rates', type_='unique')
    # ### end Alembic commands ###
