name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run tests and generate coverage report
        run: |
          cd src
          poetry run coverage run -m pytest --maxfail=1 --disable-warnings -q
          poetry run coverage html --omit="*test*"

      - name: Generate coverage badge
        run: |
          cd src
          rm -f ../coverage.svg
          poetry run coverage-badge -o ../coverage.svg

      - name: Commit updated badge
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add coverage.svg
          if ! git diff-index --quiet HEAD; then
            git commit -m "actions: update coverage badge"
            git push
          else
            echo "No changes in coverage badge."
          fi